name: mockertimtest
favicon: null
layout_spectrum: 0.06963431788608432
typography_spectrum: 0.3261756969150156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.15808181837201118
  lightness: 0.7060607364401221
  saturation: 0.781378214713186
  rhythmicContrast: 0.20870788511820138
purpose: []
